firebolt-db/firebolt-sqlalchemy

README.md
setup.cfg
tests/integration/conftest.py

This setting automatically registers the dialect with the sqlalchemy so the users don't need to manually call `registry.register`
https://docs.sqlalchemy.org/en/14/core/connections.html#registering-new-dialects

feat: Removing explicit dialect register

---

src/firebolt_db/firebolt_connector.py

Redash was relying on old implementation when DBAPI layer was present in the sqlalchemy connector: https://github.com/getredash/redash/blob/master/redash/query_runner/firebolt.py#L2
This aims to make the current module compatible while Redash connector is moving to use the SDK.
Testing: verified functionality by installing the module locally and accessing the Connection class as in redash query_runner.

fix: temporary Redash compatibility

---

.github/workflows/python-integration-tests.yml
.github/workflows/release.yml
tests/integration/conftest.py

Sqlalchemy uses a different env variable for url override. Also removing nest_asyncio.

ci: fix environment variable name

---

README.md

Some special characters cause failures in auth. Need to make it obvious to sanitise the password as per sqlalchemy doc.

docs: Add password sanitisation in readme

---

src/firebolt_db/firebolt_async_dialect.py
src/firebolt_db/firebolt_dialect.py
tests/integration/test_sqlalchemy_integration.py
tests/unit/conftest.py
tests/unit/test_firebolt_dialect.py

Ability to pass set parameters to the cursor. Since sqlalchemy is firm on `execute()` signature those have to be passed via the connection string.

feat: Adding set parameters

---

README.md

This change has already been released. This PR is just adding docs.

docs: Adding account name

---

src/firebolt_db/firebolt_dialect.py
tests/unit/test_firebolt_dialect.py

Can't run sqlalchemy in lambda without it.

feat: Turn off token cache param

---

src/firebolt_db/firebolt_dialect.py
tests/integration/test_sqlalchemy_async_integration.py
tests/integration/test_sqlalchemy_integration.py
tests/unit/test_firebolt_dialect.py

Allowing user override autodetected clients and drivers and provide their own.
Also fixing incorrect test which I suspect are due to a change in information schema querying.

feat: Client tracking args

---

.github/workflows/nightly.yml
setup.cfg

Also updating setup.cfg to be in line with SDK python requirements and version (needed for tracker overrides).

ci: Adding nightly job

---

src/firebolt_db/firebolt_async_dialect.py
src/firebolt_db/firebolt_dialect.py
tests/integration/test_sqlalchemy_async_integration.py
tests/integration/test_sqlalchemy_integration.py
tests/unit/test_firebolt_dialect.py

This allows for the following:
```
connection.execute("SET my_param=1")
connection.execute("SELECT FROM some_param_dependent_table")
```
Before the only way to provide parameters was via the connection string.

feat: Allow set parameters as queries

---

setup.cfg
src/firebolt_db/firebolt_async_dialect.py
tests/unit/test_firebolt_async_dialect.py

Also removing the leftover set parameter logic. All of it lives in `firebolt_dialect.py`

chore: unpin SDK version

---

.github/workflows/nightly.yml
.github/workflows/python-integration-tests.yml
.github/workflows/release.yml
.legitignore
src/firebolt_db/firebolt_dialect.py
tests/integration/conftest.py
tests/integration/test_sqlalchemy_integration.py
tests/unit/test_firebolt_dialect.py

Adding support for service account. Similar to other drivers we're checking for @ symbol in username to detect a username password combination. Service account id is a uuid so it would never contain this symbol.

feat: Service account support

---

setup.cfg
src/firebolt_db/firebolt_dialect.py
tests/integration/conftest.py
tests/integration/test_sqlalchemy_integration.py

With sqlalchemy 2.0.1 our tests are failing. Some of the functionality that has been deprecated has been removed now.
This is correcting some of the function signatures and the way we call them. Also adding a library that's used in tests but no longer used in sqlalchemy.
Tests are passing for both sqlalchemy==1.* and 2.0.1

test: Compatibility with alchemy 2.0.1

---

.github/workflows/code-check.yml
.pre-commit-config.yaml
tests/integration/test_sqlalchemy_async_integration.py

Analogous to fix in https://github.com/firebolt-db/firebolt-python-sdk/pull/238
This is needed since isort no longer works with an update to one of its dependencies.

ci: Fix pre-commit

---

src/firebolt_db/firebolt_dialect.py
tests/integration/conftest.py
tests/integration/test_sqlalchemy_integration.py

Support new types, rework Array type and add catch-all VARCHAR type.
This also fixes the issue in FIR-23053, confirmed in Superset.

feat: New firebolt types

---

.github/workflows/nightly.yml

ci: Remove foresight

---

README.md

Change links to the current 2.0 version of sqlalchemy docs

docs: Update links to 2.0 in README

---

.github/workflows/nightly.yml
.github/workflows/python-integration-tests.yml

using cache in the ci in order to re-run only the failed tests in order to save some time

ci: caching failed tests for re-run

---

.github/workflows/release.yml

Updated release.yml to call integration tests from `python-integration-tests.yml` instead of running them manually

ci: call integration tests from release

---

src/firebolt_db/firebolt_dialect.py
tests/unit/test_firebolt_dialect.py

We had a bug when account name was required despite using a username password authentication.

fix: Make account name optional

---

.github/workflows/integration-tests-v1.yml
.github/workflows/integration-tests-v2.yml
.github/workflows/nightly-v1.yml
.github/workflows/nightly-v2.yml
.github/workflows/unit-tests.yml

It's no longer supported, using 3.11 in Nightlies instead.

build: Retire Python 3.7

---

src/firebolt_db/firebolt_dialect.py

This PR addresses two warnings coming from SqlAlchemy:
* `SADeprecationWarning` when sqlalchemy version 2 when creating the engine
* `SAWarning` because the attribute `supports_statement_cache` is not set
If I run this code on sqlalchemy `2.0.29`  I get these warnings:
```python
from sqlalchemy import create_engine, text
import urllib.parse
FIREBOLT_USERNAME = ...
FIREBOLT_PASSWORD = ...
DEFAULT_REGION = ...
SECRET = urllib.parse.quote_plus(FIREBOLT_PASSWORD)
database_name = ...
engine_name = ...
account_name = ... 
uri = f"firebolt://{FIREBOLT_USERNAME}:{SECRET}@{database_name}/{engine_name}?account_name={account_name}"
engine = create_engine(uri)
with engine.connect() as conn:
conn.execute(text('SELECT 1;'))
```
```
SADeprecationWarning: The dbapi() classmethod on dialect classes has …
```

fix: Addresses SA warnings

---

src/firebolt_db/firebolt_async_dialect.py

Resolves #96 
SQLAlchemy 2.0.28+ requires async dialects to explicitly define async pool class.

fix: Specify async queue pool for async dialect

---

.github/workflows/nightly-v1.yml
.github/workflows/nightly-v2.yml

As referenced in https://github.com/actions/setup-python/issues/852 there are issues with setup python and the latest macos runner. Limiting it to 13 to allow tests to pass.

ci: Limit macos runner to version 13

---

setup.cfg

Bump to make sure the users get the latest features like autostart of the engines.

build: Update Firebolt SDK to at least 1.5

---

README.md

Firebolt supports transactions now, but we don't have them implemented in SQLAlchemy.

docs(NoTicket): Clarify no transaction support in the readme
